web: PYTHONUNBUFFERED=1 PORT=5000 OAUTHLIB_INSECURE_TRANSPORT=1 RAILWAY_ENVIRONMENT=production python main.py
discord_bot: PYTHONUNBUFFERED=1 PORT=5001 RAILWAY_ENVIRONMENT=production python discord_bot.py
telegram_bot: PYTHONUNBUFFERED=1 PORT=5002 RAILWAY_ENVIRONMENT=production python telegram_bot.py
